### ISSUE TITLE
Why do you practice censorship?

### ISSUE THREAD

**Issue by baimafeima** [DataDrake/datadrake.github.io#1]
You've just deleted my comment on Phabicator. I would like to know for what reason. Practicing censorship is not exactly making you friends.

**Comment by DataDrake** [comment]
I am not censoring you, I am exercising my right as a moderator to remove off-topic philosophical messages that are unwelcome on our bug-tracker. Phab is a place for users to get help, call out specific technical issues with Solus, and to request new features and packages. It is not a forum for users to spread their political and philosophical ideals. 

Additionally, please refrain from contacting me in this manner. It is not only unwelcome, but unprofessional. I have a multiple email addresses. You are welcome to make use of them to contact me.

**Comment by baimafeima** [comment]
> I am exercising my right as a moderator to remove off-topic philosophical messages that are unwelcome on our bug-tracker.

You are not exercising your right, you are misusing your power. What specific issue are you referring to here? I was commenting on `FreeTube` which I praised as a good example of preventing "nasty tracking cookies" if I remember correctly (unfortunately, you've deleted the message, so that there is no public record). I'm not sure to what extent this is in any way harmful to the bug-tracker or the Solus community as a whole. In addition to deleting my comment, you have disabled my account. I have to ask you whether you are putting personal animosities over factual matters here. 

> 

> Additionally, please refrain from contacting me in this manner. It is not only unwelcome, but unprofessional. I have a multiple email addresses. You are welcome to make use of them to contact me.

No, what you have done wasn't professional. Not only have you deleted a comment which surely didn't offend anyone. Secondly, you have deactivated my account on the bug tracker. As a general rule, I prefer to keep things public when they belong to the public and this is clearly such an issue. Why should I privately send an email to you when there is nothing private to talk about?

**Comment by baimafeima** [comment]
To be clear, I request that you:
1. Restore _this_ particular message (the one which prompted this conversation) for the public record. 
2. Re-activate my account on phabricator. 
3. Un-ban my access to the IRC community. 

I hope you do not escalate this any further. Thank you.

**Comment by DataDrake** [comment]
This isn't about personal animosity or an abuse of power. It's about professional courtesy. You have been asked several times now to stop posting messages like that and to cease similar discussions on IRC. Now you are trying to publicly shame me in an attempt to get your way. I didn't make this personal, but you are.

* I will not restore your messages on Phabricator as you have already been publicly and privately told not to post messages like that in the past. I have not singled use out in this matter and have removed other similar posts from several other users for the same reasons. 

* I am willing to consider reactivation of your account if you will be professional and cease this tirade of forcing your philosophical ideals on me and the Solus Project. To date, you have been unable to do that on IRC (which was the reason for your ban in the first place) and Phabricator.

* I asked that you contact me via email because Github issues on random personal projects are an inappropriate channel for these communication and you have forced me and others on the project to remove your access from the other public forums of communication.

Note that I view this as a clarification of the current state of affairs and not an escalation of this issue. I again would stress that this is a result of your unwillingness to adhere to the requests of myself and others and not at all an attempt to censor your personal opinions. This was not an action that I took lightly and was made in agreement with other members of the Solus Core Team.

**Comment by baimafeima** [comment]
Once my previous messages are restored we can return to **facts** and have a common basis to refer to. 

Alternatively, feel free to post my very **last comment** on Phabricator here for us to analyze the **specific** issue at hand (which prompted you to deactivate my account within seconds after I posted it) and what specifically you didn't like about it. The sad truth of the matter is - given the fact that you deliberately censor my posts - that I have no way of factually refering to them and you make me appear as if I was in any way offending anyone which I clearly wasn't.

**Comment by DataDrake** [comment]
The facts are simple. You have been asked to stop this behavior on multiple occasions and have refused to do so. In light of that continued refusal, your accounts have been disabled. It isn't a matter of whether or not you have offended any one. It is the fact that you are refusing to comply with our requests, as the Core Team of Solus, for you to cease and desist this specific behavior. It is perfectly within our rights to refuse you access if you are unwillingly to comply with our expectations and guidelines.

I am not arguing the validity of your philosophical or political ideals. Nor am I attempting to censor them from the public. That is not what is it at issue here. The purpose of the Solus Bug Tracker (Phabricator) is  **technical discussion**, not philosophical and political debate. Your _repeated_ attempts to appeal to us in this manner as a means of arguing for the inclusion of software into the repo are unwelcome as they are not wholly technical. Solus cares about your security and privacy, however, that does not mean that every application that promises additional privacy or security (over our current offerings) is guaranteed to be accepted for inclusion. We reserve the right to refuse inclusion of any piece of software we choose and this is clearly spelled out in our Package Inclusion Policy.

At this point in time, it is clear that you do not agree with my assessment of the situation. That doesn't however change how the rest of us see this situation. I have no further comment to give and believe I have clearly and concisely explained myself. As such, I will be locking this issue from further discussion. Again you may feel free to contact me through email for further discussion. Further attempts to communicate with me via "random" Issues on GitHub repositories either owned by myself or the Solus Project will be treated as harassment and reported to GitHub proper.
